version: "3.9"

services:
  backend:
    build: .
      # Image Docker du backend publiée sur Docker Hub
    image: deparfouruliam/react-f-api:latest

    # Nom du conteneur (optionnel mais pratique)
    container_name: backend

    # Port exposé (host:container)
    ports:
      - "8000:8000"

    # Réseau privé Docker utilisé par le service
    networks:
      - app_network

  frontend:
    build:
      context: ./my-react-app
      args:
        VITE_API_URL: http://backend:8000
    # Image Docker du frontend publiée sur Docker Hub
    image: deparfouruliam/frontend:latest

    container_name: frontend

    ports:
      - "8080:80"

    # Le frontend dépend du backend
    depends_on:
      - backend

    networks:
      - app_network

# Définition des réseaux Docker
networks:
  app_network:
    # Réseau privé interne à Docker
    driver: bridge